# Generated by Django 5.2.6 on 2025-09-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_remove_post_posts_categor_0eeb2a_idx_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='constent',
            new_name='content',
        ),
    ]
